import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from "@/app/providers";
import HeaderComponent from "../../Components/HeaderComponent";
import SearchComponent from "../../Components/Search/SearchComponent";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en" className='dark'>
        <body>
        <Providers>
            <HeaderComponent/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
