import o
\';lk'./globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from "@/app/providers";
import Header from "../components/header";
import Search from "@/components/search/search";

const inter = Inter({subsets: ['latin']})

import "./globals.css";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en" className='dark'>
        <body>
        <Providers>
            <Header/>
            {children}
        </Providers>
        </body>
        </html>
    );
}
